import turtle
rainbow = ('red','orange','yellow','green','cyan','blue','purple')
turtle.left(20)
for color in rainbow:
    turtle.left(20)
    turtle.fillcolor(color)
    turtle.begin_fill()
    turtle.forward(120)
    turtle.left(90)
    turtle.circle(120,20)
    turtle.left(90)
    turtle.forward(150)
    turtle.right(90)
    turtle.circle(-30,20)
    turtle.right(90)
    turtle.forward(30)
    turtle.end_fill()
    turtle.left(30)
turtle.done()
